title: blog
description: A bolg.
author: Shangzhi wang
avatar: /logo.png
email: 451155928@qq.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: none
  card: none
logo: logo.png
social:
  name: Shangzhi wang
  links:
    - http://wangrangzhi.github.io/
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
